# Generated by Django 2.2.6 on 2020-08-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('create_time',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
