# Generated by Django 2.2.6 on 2019-10-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('Air_wendu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='空气温度')),
                ('Air_shidu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='空气湿度')),
            ],
            options={
                'verbose_name': '空气数据',
                'verbose_name_plural': '空气数据',
                'db_table': 'df_airdata',
            },
        ),
        migrations.CreateModel(
            name='GroundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tu_place', models.CharField(max_length=20, verbose_name='土地位置')),
                ('tu_depth', models.IntegerField(default=20, verbose_name='土壤深度')),
                ('tu_shidu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='土壤湿度')),
                ('tu_wendu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='土壤温度')),
            ],
            options={
                'verbose_name': '土壤数据',
                'verbose_name_plural': '土壤数据',
                'db_table': 'df_grounddata',
            },
        ),
    ]
