# Generated by Django 2.2.6 on 2019-10-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEexel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('auto_flag', models.SmallIntegerField(choices=[(0, '手动'), (1, '自动')], default=0)),
                ('place', models.CharField(max_length=20, verbose_name='阀门位置')),
                ('tu_depth', models.IntegerField(default=0, verbose_name='土壤深度')),
                ('grow_circle', models.CharField(max_length=20, verbose_name='作物生长周期')),
                ('start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('stop_time', models.DateTimeField(verbose_name='计划结束时间')),
            ],
            options={
                'verbose_name': '控制表',
                'verbose_name_plural': '控制表',
                'db_table': 'df_controlexcel',
            },
        ),
        migrations.CreateModel(
            name='XiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('Ke', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='系数Ke')),
                ('Kec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='系数Kec')),
                ('Ku', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='系数Ku')),
                ('grow_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ControlEexel', verbose_name='生长周期外键')),
            ],
            options={
                'verbose_name': '比例系数表',
                'verbose_name_plural': '比例系数表',
                'db_table': 'df_xidata',
            },
        ),
        migrations.CreateModel(
            name='FuzzySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('cha_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='差值')),
                ('zhengteng_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='误差变化率')),
                ('water_length', models.IntegerField(default=0, verbose_name='灌溉时间')),
                ('grow_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.ControlEexel', verbose_name='生长周期外键')),
                ('xi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.XiData', verbose_name='比例系数外键')),
            ],
            options={
                'verbose_name': 'fuzzy查询表',
                'verbose_name_plural': 'fuzzy查询表',
                'db_table': 'df_fuzzytable',
            },
        ),
    ]
