# Generated by Django 2.2.6 on 2019-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20191015_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleexel',
            name='auto_flag',
            field=models.SmallIntegerField(choices=[(0, '手动'), (1, '自动')], default=0),
        ),
    ]
