# Generated by Django 2.2.6 on 2022-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20221226_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleexel',
            name='auto_flag',
            field=models.SmallIntegerField(choices=[(0, '手动'), (1, '自动')], default=0),
        ),
    ]
