# Generated by Django 2.2.6 on 2022-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20221226_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleexel',
            name='auto_flag',
            field=models.SmallIntegerField(choices=[(1, '自动'), (0, '手动')], default=0),
        ),
    ]
