# Generated by Django 2.2.6 on 2019-10-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('status_name', models.CharField(max_length=20, verbose_name='设备名称')),
            ],
            options={
                'verbose_name': '设备名称',
                'verbose_name_plural': '设备名称',
                'db_table': 'df_statusname',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('temprature', models.IntegerField(verbose_name='温度')),
                ('vol', models.IntegerField(default=0, verbose_name='电压')),
                ('power', models.IntegerField(default=0, verbose_name='电量')),
                ('place', models.CharField(max_length=20, verbose_name='放置状态')),
                ('status_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.StatusName', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备状态',
                'verbose_name_plural': '设备状态',
                'db_table': 'df_status',
            },
        ),
    ]
