# Generated by Django 2.2.6 on 2019-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20191015_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='place',
            field=models.CharField(max_length=20, verbose_name='放置位置'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=20, verbose_name='设备名称'),
        ),
        migrations.DeleteModel(
            name='StatusName',
        ),
    ]
