# Generated by Django 2.2.6 on 2022-12-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
